---
title: "r-101-grade"
author: "Iris Mancini"
format: html
editor: visual
code-fold: true
---

```{r, message = FALSE}
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(vroom)
```

### Q1.Data loading : 

```{r, message = FALSE}

grades <- vroom(here("grades.csv"))
```

### Q.2. 

```{r, message = FALSE, echo = FALSE}
summarize <- grades |> 
  summarise(Minimum = min(Exam, na.rm=TRUE), Maximum = max(Exam, na.rm=TRUE), Median = median(Exam, na.rm=TRUE), Mean = mean(Exam, na.rm=TRUE))

summarize |>
  knitr::kable()
  
```

### Q.3 : 

```{r, message = FALSE, echo = FALSE}
exam_na <-  grades |>
  filter(is.na(Exam)) |>
  count(is.na(Exam))
```

There are `r exam_na` students who didn't take the Exam.

### Q.4 : 

```{r, message = FALSE}
grades |> 
  drop_na(Exam) |>
ggplot(aes(x = Exam)) + 
  geom_histogram(binwidth = 4, fill = "lightblue", color = "white") + 
  xlab("Grade at the Exam") + ylab("absolute frequencies") + 
  labs(title = "Distribution of the grades") + 
   theme(plot.title = element_text(hjust = 0.5))
  
```

### Q5. 

```{r}

```
